[[intro]]
== Introduction

RISC-V hardware performance monitoring counters (Zihpm) provide support for counting performance events, and, with Sscofpmf, support basic, interrupt-based performance event sampling. These extensions provide a means for collecting performance event counts across a window of software execution.

This specification defines extensions that provide advanced performance event sampling capabilities for RISC-V harts.  They enable precise attribution of performance events, and collection of runtime execution metadata for sampled instructions.  Such capabilities allow developers to much more precisely identify the instructions and functions that incur bottlenecks, and target them for tuning.

The *Ssplcofi* ISA extension ('Ss' for supervisor level, 'p' for precise, 'lcofi' for local counter overflow interrupt) guarantees precise delivery of LCOFIs, for select events.  Once a counter programmed to count such an event overflows, it is guaranteed that the LCOFI immediately follows an instruction that incurred the event.  This allows the event to be precisely attributed to the instruction.

The *Sspesa* ISA extension ('Ss' for supervisor level, 'pesa' for precise event sample attribution) allows for precise attribution without requiring precise interrupts.  Instead, it records a sample PC and sample metadata at the time of overflow which, for select events, allows reconstruction of the PC of the instruction that caused the overflow.

[NOTE]
====
_The Ssplcofi extension should be considered the "more precise" of the two extensions above, as it allows not only precise attribution of the event to a PC, but also allows collection of additional hart state (call-stack, GPRs, etc) associated with that sampled instruction.  With Sspesa, only the attribution PC is available.  Any other hart state may have been altered as a result of interrupt skid, which can allow instructions to retire between that which caused overflow and the actual trap._

_Where Sspesa may be preferred is in high-performance implementations, where implementation of precise interrupts can be very costly._
====

WARNING: more to come here, further extensions WIP